const KEY="dental_mobile_v2";let db=JSON.parse(localStorage.getItem(KEY)||"null")||{patients:[],plans:{},payments:{},visits:{},appointments:[],expenses:[],settings:{clinic:"Dental Clinic",doctor:"د. أحمد"}};let current=null,toothNo=null,day=new Date();const $=x=>document.getElementById(x),money=n=>(+n||0).toLocaleString()+" ج.م",date=d=>d.toISOString().slice(0,10),save=()=>localStorage.setItem(KEY,JSON.stringify(db));
function go(id){document.querySelectorAll("section").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");document.querySelectorAll(".bottom button").forEach(b=>b.classList.toggle("active",b.dataset.go===id));({dashboard,patients,calendar,finance,settings})[id]?.()}
document.querySelectorAll(".bottom button").forEach(b=>b.onclick=()=>go(b.dataset.go));
function modal(id,on=true){$(id).classList.toggle("hidden",!on)}
$("quickAdd").onclick=$("addPatient").onclick=()=>modal("patientModal");$("closePatient").onclick=()=>modal("patientModal",false);
$("savePatient").onclick=()=>{let n=$("newName").value.trim();if(!n)return alert("اكتب اسم المريض");db.patients.push({name:n,phone:$("newPhone").value,age:$("newAge").value,allergy:$("newAllergy").value});save();modal("patientModal",false);patients();dashboard()};
$("search").oninput=e=>patients(e.target.value);
function patients(q=""){let a=db.patients.filter(p=>(p.name+" "+p.phone).includes(q));$("patientList").innerHTML=a.map(p=>{let i=db.patients.indexOf(p);return `<div class="patient" onclick="openProfile(${i})"><b>${p.name}</b><div class="sub">${p.phone||"—"} · ${p.age||"—"} سنة · ${p.allergy||"لا توجد حساسية"}</div></div>`}).join("")||`<div class="panel">لا يوجد مرضى.</div>`}
window.openProfile=i=>{current=i;let p=db.patients[i];$("pName").textContent=p.name;$("phone").value=p.phone||"";$("age").value=p.age||"";$("allergy").value=p.allergy||"";$("medical").value=p.medical||"";buildTeeth();profileRender();go("profile")};
$("back").onclick=()=>go("patients");$("saveProfile").onclick=()=>{let p=db.patients[current];p.phone=$("phone").value;p.age=$("age").value;p.allergy=$("allergy").value;p.medical=$("medical").value;save();alert("تم الحفظ")};
function buildTeeth(){["upper","lower"].forEach(x=>$(x).innerHTML="");[18,17,16,15,14,13,12,11,21,22,23,24,25,26,27,28,48,47,46,45,44,43,42,41,31,32,33,34,35,36,37,38].forEach((n,i)=>{let d=document.createElement("div");d.className="tooth";d.textContent=n;d.onclick=()=>{toothNo=n;document.querySelectorAll(".tooth").forEach(t=>t.classList.remove("sel"));d.classList.add("sel");$("toothBox").classList.remove("hidden");$("toothTitle").textContent="Tooth "+n};$(i<16?"upper":"lower").appendChild(d)})}
$("saveTooth").onclick=()=>{if(toothNo==null)return alert("اختر سنًا");db.plans[current]??=[];db.plans[current].push({tooth:toothNo,surface:$("surface").value,status:$("status").value,diagnosis:$("diag").value,treatment:$("treat").value,price:+$("price").value||0});save();profileRender();alert("تم حفظ علاج السن")};
function profileRender(){let a=db.plans[current]||[],pay=(db.payments[current]||[]).reduce((s,x)=>s+x.amount,0),total=a.reduce((s,x)=>s+x.price,0);$("plan").innerHTML=a.map(x=>`<div class="row"><span><b>${x.tooth}</b> ${x.surface} — ${x.treatment||"—"}<br><small>${x.diagnosis||"—"} · ${x.status}</small></span><b>${money(x.price)}</b></div>`).join("")||"لا يوجد علاج";$("total").textContent=money(total);$("paid").textContent=money(pay);$("remain").textContent=money(Math.max(0,total-pay));$("visits").innerHTML=(db.visits[current]||[]).map(v=>`<div class="row"><span>${v.date}</span><span>${v.treatment||""}</span></div>`).join("")||"لا توجد زيارات"}
$("payment").onclick=()=>modal("paymentModal");$("closePay").onclick=()=>modal("paymentModal",false);$("savePay").onclick=()=>{let n=+$("payAmount").value||0;if(n<=0)return alert("أدخل المبلغ");db.payments[current]??=[];db.payments[current].push({amount:n,method:$("payMethod").value,date:new Date().toLocaleDateString("ar-EG")});save();modal("paymentModal",false);profileRender();finance();dashboard()};
$("visit").onclick=()=>modal("visitModal");$("closeVisit").onclick=()=>modal("visitModal",false);$("saveVisit").onclick=()=>{db.visits[current]??=[];db.visits[current].push({date:new Date().toLocaleDateString("ar-EG"),diagnosis:$("vDiag").value,treatment:$("vTreat").value});save();modal("visitModal",false);profileRender()};
$("appointment").onclick=()=>{ $("aPatient").innerHTML=db.patients.map((p,i)=>`<option value="${i}">${p.name}</option>`).join("");$("aDate").value=date(day);$("aTime").value="10:00";modal("apptModal")};$("closeAppt").onclick=()=>modal("apptModal",false);$("saveAppt").onclick=()=>{let i=+$("aPatient").value;if(!db.patients[i])return alert("أضف مريضًا أولاً");db.appointments.push({patient:db.patients[i].name,date:$("aDate").value,time:$("aTime").value,procedure:$("aProcedure").value,status:$("aStatus").value});save();modal("apptModal",false);calendar();dashboard()};
$("prev").onclick=()=>{day.setDate(day.getDate()-1);calendar()};$("next").onclick=()=>{day.setDate(day.getDate()+1);calendar()};
function calendar(){$("calTitle").textContent=day.toLocaleDateString("ar-EG",{weekday:"long",day:"numeric",month:"long"});let a=db.appointments.filter(x=>x.date===date(day));$("calList").innerHTML=a.map(x=>`<div class="row"><span><b>${x.time}</b> ${x.patient}<br><small>${x.procedure||""}</small></span><span class="badge">${x.status}</span></div>`).join("")||"<div style='padding:20px;text-align:center;color:#708096'>لا توجد مواعيد</div>"}
$("expense").onclick=()=>modal("expenseModal");$("closeExp").onclick=()=>modal("expenseModal",false);$("saveExp").onclick=()=>{let n=$("eName").value,a=+$("eAmount").value||0;if(!n||!a)return alert("أدخل البيانات");db.expenses.push({name:n,amount:a,date:new Date().toLocaleDateString("ar-EG")});save();modal("expenseModal",false);finance();dashboard()};
function finance(){let p=Object.values(db.payments).flat(),r=p.reduce((s,x)=>s+x.amount,0),e=db.expenses.reduce((s,x)=>s+x.amount,0);$("fRev").textContent=money(r);$("fExp").textContent=money(e);$("fNet").textContent=money(r-e);$("fCard").textContent=money(p.filter(x=>x.method==="Card").reduce((s,x)=>s+x.amount,0));$("transactions").innerHTML=[...p.map(x=>`<div class="row"><span>💳 ${x.method}</span><b>${money(x.amount)}</b></div>`),...db.expenses.map(x=>`<div class="row"><span>🔻 ${x.name}</span><b>-${money(x.amount)}</b></div>`)].join("")||"لا توجد حركات"}
function dashboard(){let t=date(new Date()),a=db.appointments.filter(x=>x.date===t),p=Object.values(db.payments).flat(),plans=Object.values(db.plans).flat(),r=p.reduce((s,x)=>s+x.amount,0),tot=plans.reduce((s,x)=>s+x.price,0);$("dPatients").textContent=db.patients.length;$("dAppointments").textContent=a.length;$("dRevenue").textContent=money(r);$("dRemaining").textContent=money(Math.max(0,tot-r));$("today").innerHTML=a.map(x=>`<div class="row"><span>${x.time} · ${x.patient}</span><span class="badge">${x.status}</span></div>`).join("")||"لا توجد مواعيد اليوم"}
$("saveSettings").onclick=()=>{db.settings.clinic=$("clinic").value;db.settings.doctor=$("doc").value;save();loadSettings();alert("تم الحفظ")};function loadSettings(){$("clinic").value=db.settings.clinic;$("doc").value=db.settings.doctor;$("title").textContent="🦷 "+db.settings.clinic;$("doctor").textContent=db.settings.doctor}
$("backup").onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}));a.download="dental-clinic-backup.json";a.click()};$("restore").onchange=e=>{let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();location.reload()}catch(x){alert("النسخة غير صالحة")}};r.readAsText(e.target.files[0])};
$("print").onclick=()=>{let p=db.patients[current],a=db.plans[current]||[],w=window.open();if(!w)return;w.document.write(`<html dir=rtl><body style="font-family:Arial;padding:25px"><h1>${db.settings.clinic}</h1><h2>${p.name}</h2>${a.map(x=>`<p>Tooth ${x.tooth} — ${x.treatment} — ${x.price} ج.م</p>`).join("")}</body></html>`);w.document.close();w.print()};
loadSettings();patients();dashboard();calendar();finance();go("dashboard");
